---
Name: silverware-portfolio
---

# Configure Portfolio Project Controller:

SilverWare\Portfolio\Pages\PortfolioProjectController:
  required_js:
    - "silverware/portfolio: client/dist/js/bundle.js"
  required_css:
    - "silverware/portfolio: client/dist/styles/bundle.css"
